version: 0.2

phases:
  install:
    commands:
      - echo Enter install phase
      - n 18.15.0
      - node -v
      - npm -v
      - npm install

  build:
    commands:
      - echo Enter build phase
      - npm run build
      # Remove js.map files
      - find ./build -iname '*.js.map' -type f -delete

  post_build:
    commands:
      - echo Enter S3 deployment phase
      - bash deploy.sh
